name: omniauth-nitro-id

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@main
    with:
      package: '${{ github.workflow }}'
      ruby: '["2.7", "3.0", "3.1"]'
    secrets: inherit
