name: omniauth-nitro-id

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@main
    with:
      package: '${{ github.workflow }}'
      ruby: '["3.1", "3.2", "3.3"]'
    secrets: inherit
