name: omniauth-nitro-id

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@510462bdde0342c8fd47def5102734a8e5de347d # main
    with:
      package: '${{ github.workflow }}'
      ruby: '["2.7", "3.0", "3.1"]'
    secrets: inherit
