name: omniauth-nitro-id

on:
  push:

jobs:
  ruby:
    uses: powerhome/power-tools/.github/workflows/_ruby-workflow.yml@main
    with:
      package: '${{ github.workflow }}'
      ruby: '["2.7", "3.0", "3.1"]'
    secrets: inherit
